### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Yaguang0990** [Countly/countly-sdk-android#117]
2020-08-07 15:21:59.276 908-1242/system_process E/WifiVendorHal: getWifiLinkLayerStats_1_3_Internal(l.927) failed {.code = ERROR_NOT_SUPPORTED, .description = }
2020-08-07 15:21:59.455 30554-30569/... W/System: A resource failed to call close. 
2020-08-07 15:22:00.002 1292-1292/com.android.systemui W/TrClockView: Keyguard is not showing,so we do not update time.
2020-08-07 15:22:00.010 3265-3265/...r E/NetworkUtil: networkInfo.getExtraInfo() is TYPE_WIFI
2020-08-07 15:22:00.430 30554-30554/... W/...: Throwing OutOfMemoryError "Failed to allocate a 61603848 byte allocation with 25165824 free bytes and 35MB until OOM, target footprint 122292888, growth limit 134217728" (VmSize 1428100 kB)
2020-08-07 15:22:00.609 30554-30554/... W/...: Throwing OutOfMemoryError "Failed to allocate a 61603848 byte allocation with 25165824 free bytes and 35MB until OOM, target footprint 122292888, growth limit 134217728" (VmSize 1428100 kB)
2020-08-07 15:22:00.609 30554-30672/... W/...: Long monitor contention with owner main (30554) at void ly.count.android.sdk.Countly.onStop()(Countly.java:-1) waiters=0 in boolean ly.count.android.sdk.Countly.isLoggingEnabled() for 949ms
2020-08-07 15:22:00.610 30554-30554/... E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ..., PID: 30554
    java.lang.OutOfMemoryError: Failed to allocate a 61603848 byte allocation with 25165824 free bytes and 35MB until OOM, target footprint 122292888, growth limit 134217728
        at java.util.Arrays.copyOf(Arrays.java:3257)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:137)
        at ly.count.android.sdk.CountlyStore.join(CountlyStore.java:392)
        at ly.count.android.sdk.CountlyStore.addConnection(CountlyStore.java:157)
        at ly.count.android.sdk.ConnectionQueue.recordEvents(ConnectionQueue.java:464)
        at ly.count.android.sdk.Countly.sendEventsIfExist(Countly.java:1658)
        at ly.count.android.sdk.ModuleSessions.endSessionInternal(ModuleSessions.java:55)
        at ly.count.android.sdk.Countly.onStop(Countly.java:913)
        at com.jess.arms.base.BaseActivity.onStop(BaseActivity.java:225)
        at ...mvp.ui.activity.MainActivity.onStop(MainActivity.java:545)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1473)
        at android.app.Activity.performStop(Activity.java:8021)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4808)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4786)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4861)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:181)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7605)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

**Comment by iartem** [comment]
OOM is a problem with your data - probably you record events with exceptionally huge segmentation.
