### ISSUE TITLE
Error on api 31

### ISSUE THREAD

**Issue by am3n** [Countly/countly-sdk-android#136]
```
java.lang.NullPointerException: Attempt to read from field 'boolean ly.count.android.sdk.ModuleCrash.recordAllThreads' on a null object reference
        at ly.count.android.sdk.Countly$4.uncaughtException(Countly.java:1320)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:574)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by ArtursKadikis** [comment]
Hello, which SDK version were you using? Can you maybe provide some additional information about the circumstances?

**Comment by am3n** [comment]
hi

RUN:
1- Emulator Google Play API 31
2- Xiaomi Redmi note 8 Android 11

APP:
compileSdkVersion 31
targetSdkVersion 31
countly sdk: 20.11.11


And Fixed by adding
```implementation "com.google.firebase:firebase-core:17+"```

Tnx
