### ISSUE TITLE
Got exception while trying to submit event data

### ISSUE THREAD

**Issue by RandyHBH** [Countly/countly-sdk-android#82]
Hi, guys, I'm running Countly Opensource Server from docker, and I have this basic setup

This is my server address 
`private val countlyServerUrl: String = "http://192.168.1.244:32768"`

basic initialization
```
Countly.sharedInstance().isLoggingEnabled = true
Countly.sharedInstance().enableCrashReporting()
Countly.sharedInstance().init(application.applicationContext, countlyServerUrl, countlyAppKey, null, DeviceId.Type.ADVERTISING_ID)
Countly.sharedInstance().setLocation(getCountryCode(), getActualCity(), null, null)
```
and i am sending a basic event
`Countly.sharedInstance().recordEvent("Something")`  

but when i run the app from my phone and  the  search in the logs, give me this exception while trying to submit event data
```
java.net.ProtocolException: Unexpected status line: <html>
at com.android.okhttp.internal.http.StatusLine.<init>(StatusLine.java:38)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:197)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:103)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:677)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:403)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:347)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:515)
at ly.count.android.sdk.ConnectionProcessor.run(ConnectionProcessor.java:208)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

So, any help will be much appreciated

**Comment by iartem** [comment]
Hi Randy. Your server doesn't seem to be running well. Or may be it's inaccessible from phone.

**Comment by ArtursKadikis** [comment]
Can you check if you can open the server dashboard from your phones browser? Could you also paste the full logs from running your application? There should be other messages that the SDK is outputting.

**Comment by RandyHBH** [comment]
hi, thanks for your answer, yes I can open the server dashboard from my phone browser. This is the log 
[Countly_Server_error.java.zip](https://github.com/Countly/countly-sdk-android/files/1689779/Countly_Server_error.java.zip) , hope this can be helpful.

**Comment by RandyHBH** [comment]
Any help???

**Comment by ArtursKadikis** [comment]
Could you please run our sample app (https://github.com/Countly/countly-sdk-android/tree/master/app) and then show the outputted logs? Before running, input your server url and app key.

**Comment by RandyHBH** [comment]
Already test the example app and is working, also I test my app on a device whit android 7 and is also working, but when I test the app on Android 4.4.2 and Android 5 devices is given this exception

```
02-05 10:46:49.589 3313-3347/engineering.aleph.casabeonfire W/Countly: Got exception while trying to submit event data: app_key=91c89a6123740629bb309c43717e583e82fea951&timestamp=1517508836120&hour=13&dow=4&tz=-300&sdk_version=18.01&sdk_name=java-native-android&begin_session=1&metrics=%7B%22_locale%22%3A%22en_US%22%2C%22_app_version%22%3A%221.0.0%22%2C%22_device%22%3A%22ORINOQUIA+Auyantepui%2BY221-U03%22%2C%22_resolution%22%3A%22320x480%22%2C%22_os_version%22%3A%224.4.2%22%2C%22_os%22%3A%22Android%22%2C%22_carrier%22%3A%22CUBACEL%22%2C%22_density%22%3A%22MDPI%22%7D&city=La Havana&country_code=cu&device_id=c3a38417-ffd3-4feb-9053-51d7655e44a5
                                                                       java.net.ProtocolException: Unexpected status line: <html>
                                                                           at com.android.okhttp.internal.http.RawHeaders.setStatusLine(RawHeaders.java:108)
                                                                           at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:308)
                                                                           at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:135)
                                                                           at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:644)
                                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
                                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
                                                                           at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
                                                                           at ly.count.android.sdk.ConnectionProcessor.run(ConnectionProcessor.java:208)
                                                                           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:848)
```

**Comment by ar2rsawseen** [comment]
So if you enter this in your browser:

http://yourdomain.com/i?app_key=91c89a6123740629bb309c43717e583e82fea951&timestamp=1517508836120&hour=13&dow=4&tz=-300&sdk_version=18.01&sdk_name=java-native-android&begin_session=1&metrics=%7B%22_locale%22%3A%22en_US%22%2C%22_app_version%22%3A%221.0.0%22%2C%22_device%22%3A%22ORINOQUIA+Auyantepui%2BY221-U03%22%2C%22_resolution%22%3A%22320x480%22%2C%22_os_version%22%3A%224.4.2%22%2C%22_os%22%3A%22Android%22%2C%22_carrier%22%3A%22CUBACEL%22%2C%22_density%22%3A%22MDPI%22%7D&city=La Havana&country_code=cu&device_id=c3a38417-ffd3-4feb-9053-51d7655e44a5

replacing yourdomain.com with your actual domain to countly, what does it respond?

**Comment by RandyHBH** [comment]
the response is `{" result":"Success"}`, so I suppose that is a server problem?

**Comment by ar2rsawseen** [comment]
No, the response seems to be correct
What URL are you using in the app? is it the same as you used in my provided example? Does it have https or some slashes at the end, etc?

Can you check your server logs located in countly/log/countly-api.log file to determine if server has logged any errors.

**Comment by RandyHBH** [comment]
I'm using docker countly-comunity-server so if you can tell me where I can find this logs, also this container is running locally and through http

**Comment by RandyHBH** [comment]
hi guys, I already fix the problem, this is was the issue, in the 
`Countly.sharedInstance().setLocation(getCountryCode(), getActualCity(), null, null)` part
getActualCity() was returning a city with space and this was causing the problem in earlier androids versions so, i solved checking this word haven't no spaces

**Comment by ArtursKadikis** [comment]
Good to hear that!
