### ISSUE TITLE
bugs with ScreenCam

### ISSUE THREAD

**Issue by jeremiasich** [Countly/countly-sdk-android#88]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.content.SharedPreferences.getString(java.lang.String, java.lang.String)' on a null object reference
	at com.orpheusdroid.screenrecorder.VideosListFragment.checkPermission(VideosListFragment.java:183)
	at com.orpheusdroid.screenrecorder.VideosListFragment.setUserVisibleHint(VideosListFragment.java:144)
	at android.support.v13.app.FragmentCompat$FragmentCompatApi15Impl.setUserVisibleHint(FragmentCompat.java:134)
	at android.support.v13.app.FragmentCompat.setUserVisibleHint(FragmentCompat.java:252)
	at android.support.v13.app.FragmentStatePagerAdapter.setPrimaryItem(FragmentStatePagerAdapter.java:188)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1228)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:739)
	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:91)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1361)
	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:809)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6130)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2693)
	at android.view.View.measure(View.java:19147)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2481)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1440)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1694)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6724)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by gorkem-cetin** [comment]
What is it todo with Countly? Please be specific with your issue.
